### ISSUE TITLE
Update code page data from recent Wine

### ISSUE THREAD

**Issue by unxed** [Etersoft/libnatspec#3]
Hello! I didn't know about your project, so I made my own, [very similar](https://github.com/unxed/oemcp/). I do not used Wine function calls, but extracted code page information directly from its sources.

As a result, now I have a more complete table, but you have a more accurate one. For example, my version supports Greek, but yours supports Ukrainian better and understands the difference, for example, between uz_UZ and uz_UZ@cyrillic. Apparently, you made some manual changes, not just mechanically used Wine data. But I don't know what changes you made and what data sources you used for them.

Therefore, please update get_charset_data.h using fresh Wine as basic data source. Thanks!

**Comment by vitlav** [comment]
Прошу прощения, что я не заметил вашу Issue.
Я обновил get_charset_data.h.
libnatspec, как я заметил, используется в ряде дистрибутивов. Может быть мы можем объединить усилия наших проектов?

**Comment by unxed** [comment]
Спасибо!

Про объединение. Есть кейс для него как раз.

Вот думаю, может тогда из far2l выкинуть потроха wine, и перейти на libnatspec? Или ещё лучше сделать возможными обе опции сборки, например. @elfmz что скажете?

**Comment by unxed** [comment]
Пока что для начала я у себя ссылку на вас поставил как на более свежий и полный проект, и PR с некоторыми изменениями README запульнул, а то сейчас по нему (не читая русскую версию) не совсем понятно, что именно, всё же, либа делает, и чем она, скажем, от iconv отличается.

**Comment by unxed** [comment]
Apps that can potentially benefit from libnatspec:

https://github.com/mate-desktop/engrampa/issues/5
https://sourceforge.net/p/infozip/patches/29/
https://sourceforge.net/p/p7zip/bugs/187/
